26 initial inspected points not counted towards reward
act3-ace/safe-autonomy-sims pull request #27
Opened 2024-10-23 17:44 UTC by keatincf

The fix for the issue was relatively simple, but there were a lot of mypy, flake8, and pylint warnings/errors that needed to be resolved before I could commit.

2024-10-23 19:01 UTC, jamie-cunningham requested changes
Good job on this. I left a few requested changes and some feedback. I really appreciate the handling of the mypy/formatting stuff. Some of it seems configured strangely so it may be worth the lift to configure those checks properly soon.

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +def testObservedPointsRewardEnforcesInspectedPointsCannotBeUninspected():
python functions should be snake_case

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +def testWeightedObservedPointsRewardEnforcesInspectedPointsCannotBeUninspected():
python functions should be snake_case

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_sixdof_inspection_v0.py
> +def testWeighted6DOFInspectionEnvTerminatesOnInspectionThresholdMet():
python functions should be snake_case

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_weighted_inspection_v0.py
> +def testWeightedInspectionEnvTerminatesOnInspectionThresholdMet():
python functions should be snake_case

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_sixdof_multi_inspection_v0.py
> +def testWeighted6DOFMultiInspectionEnvTerminatesOnInspectionThresholdMet():
python functions should be snake_case

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_weighted_multi_inspection_v0.py
> +def testWeightedMultiInspectionEnvTerminatesOnInspectionThresholdMet():
python functions should be snake_case

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +        pass
This looks fine but pytest has a more succinct syntax for these types of tests that allows for more flexibility:

```python
with pytest.raises(MyError):
    my_failing_function(...)
```

See [the pytest documentation](https://docs.pytest.org/en/stable/how-to/assert.html#assertions-about-expected-exceptions) for more info.

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +        pass
This looks fine but pytest has a more succinct syntax for these types of tests that allows for more flexibility:

```python
with pytest.raises(MyError):
    my_failing_function(...)
```

See [the pytest documentation](https://docs.pytest.org/en/stable/how-to/assert.html#assertions-about-expected-exceptions) for more info.

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_sixdof_inspection_v0.py
> +    env.deputy._dynamics = StaticDynamics()  # pylint: disable=W0212
These may be worth patching. The `pytest-mock` package allows for using mocks with pytest fixtures. A simpler approach might be the native `unittest.mock` package which should work just fine with pytest.

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_weighted_inspection_v0.py
> +    env.deputy._dynamics = StaticDynamics()  # pylint: disable=W0212
These may be worth patching. The `pytest-mock` package allows for using mocks with pytest fixtures. A simpler approach might be the native `unittest.mock` package which should work just fine with pytest.

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_sixdof_multi_inspection_v0.py
> +    env.chief._inspection_points = MockInspectionPointSet(parent=env.chief)  # pylint: disable=W0212
These may be worth patching. The `pytest-mock` package allows for using mocks with pytest fixtures. A simpler approach might be the native `unittest.mock` package which should work just fine with pytest.

2024-10-23 19:01 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_weighted_multi_inspection_v0.py
> +    env.chief._inspection_points = MockInspectionPointSet(parent=env.chief)  # pylint: disable=W0212
These may be worth patching. The `pytest-mock` package allows for using mocks with pytest fixtures. A simpler approach might be the native `unittest.mock` package which should work just fine with pytest.

2024-10-23 23:43 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +def testObservedPointsRewardEnforcesInspectedPointsCannotBeUninspected():
Updated name to be snake_case

2024-10-23 23:43 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +def testWeightedObservedPointsRewardEnforcesInspectedPointsCannotBeUninspected():
Updated name to be snake_case

2024-10-23 23:44 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_sixdof_multi_inspection_v0.py
> +def testWeighted6DOFMultiInspectionEnvTerminatesOnInspectionThresholdMet():
Updated name to be snake_case

2024-10-23 23:44 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_weighted_multi_inspection_v0.py
> +def testWeightedMultiInspectionEnvTerminatesOnInspectionThresholdMet():
Updated name to be snake_case

2024-10-23 23:44 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_weighted_multi_inspection_v0.py
> +    env.chief._inspection_points = MockInspectionPointSet(parent=env.chief)  # pylint: disable=W0212
Refactored to patch w/ mock class

2024-10-23 23:44 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/pettingzoo/inspection/test_sixdof_multi_inspection_v0.py
> +    env.chief._inspection_points = MockInspectionPointSet(parent=env.chief)  # pylint: disable=W0212
Refactored to patch w/ mock class

2024-10-23 23:45 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_weighted_inspection_v0.py
> +    env.deputy._dynamics = StaticDynamics()  # pylint: disable=W0212
Refactored to patch w/ mock class

2024-10-23 23:45 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_sixdof_inspection_v0.py
> +    env.deputy._dynamics = StaticDynamics()  # pylint: disable=W0212
Refactored to patch w/ mock class

2024-10-23 23:45 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +        pass
Changed to the more succinct syntax

2024-10-23 23:45 UTC, keatincf commented on test/unit_tests/safe_autonomy_sims/gym/inspection/test_reward.py
> +        pass
Changed to the more succinct syntax

2024-10-24 05:03 UTC, jamie-cunningham approved these changes

2024-10-24 14:26 UTC, merged