25 positive delta v
act3-ace/safe-autonomy-sims pull request #28
Opened 2024-10-23 21:31 UTC by JohnMcCarroll

In this PR:
- abs difference in delta_v for pettingzoo + gymnasium envs
- unit tests to ensure delta_v computed correctly

2024-10-23 21:32 UTC, JohnMcCarroll commented
Two issues keeping this from merge:
- Should delta_v be left alone, but absolute value calculated just for rewards?
- new delta_v unit tests need to be integrated with the rest of the test suite.

2024-10-29 20:33 UTC, jamie-cunningham requested changes
Overall looks great. Should be fine to merge once review comments are addressed.

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +    value
Add input type(s) to docstring

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +    value
Add return type(s) to docstring

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +def execute_strings(value):
Add type hints to input

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +def preprocess_values(value, keyword, functions):
Add type hints to input

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +    A recursive helper function to
Complete function description

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +    value
Add input type(s) to docstring

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +    value
Add return type(s) to docstring

2024-10-29 20:33 UTC, jamie-cunningham commented on test/unit_tests/safe_autonomy_sims/conftest.py
> +def read_test_cases(file_path, parameter_keywords):
Add type hints to input

2024-10-30 23:03 UTC, jamie-cunningham approved these changes

2024-10-30 23:05 UTC, merged